namespace COMP003A.Assignment1
{
    internal class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("100 Things About Me");
            Console.WriteLine("I Like Reading");
            Console.WriteLine("I Am Filipino");
            Console.WriteLine("I Love Sinigang");
            Console.WriteLine("I Love Working Out");
            Console.WriteLine("I Love Playing Video Games");
            Console.WriteLine("I Love Cars");
            Console.WriteLine("I Like Writing");
            Console.WriteLine("I Love Math");
            Console.WriteLine("I Love Coding");
            Console.WriteLine("I Like Doing Projects");
            Console.WriteLine("I Love Watching Basketball");
            Console.WriteLine("I Love Watching Football");
            Console.WriteLine("I Love Watching Boxing");
            Console.WriteLine("I Am A Curious Guy");
            Console.WriteLine("I Am A Middle Child");
            Console.WriteLine("I Love Listening To Music");
            Console.WriteLine("My Favorite Game is God Of War");
            Console.WriteLine("I Am A Fan Of Kendrick Lamar");
            Console.WriteLine("I Am A Fan Of Bruno Mars");
            Console.WriteLine("I Am A Fan Of Daniel Caesar");
            Console.WriteLine("My Favorite Music Genre is R&B");
            Console.WriteLine("I Was Born In The Philippines");
            Console.WriteLine("I Love The Color Dark Blue Grey");
            Console.WriteLine("I Believe In God");
            Console.WriteLine("I Am A Christian");
            Console.WriteLine("I Love Problem Solving");
            Console.WriteLine("I Am Loyal");
            Console.WriteLine("I Am Honest");
            Console.WriteLine("My Favorite Basketball Team Is The Golden State Warriors");
            Console.WriteLine("My Favorite Football Team Is The 49ers");
            Console.WriteLine("I Love Eating Pizza");
            Console.WriteLine("My Favorite Ice Cream Flavor is Cookies and Cream");
            Console.WriteLine("Winter Is My Favorite Season");
            Console.WriteLine("I Love The Rain");
            Console.WriteLine("I Love Sleeping");
            Console.WriteLine("I Sometimes Listen To Old Music");
            Console.WriteLine("I Am A Night Owl");
            Console.WriteLine("I Love Nature");
            Console.WriteLine("I've Never Smoked");
            Console.WriteLine("I Am Horrible At Drawing");
            Console.WriteLine("I Love Learning");
            Console.WriteLine("I Love Playing Sudoku");
            Console.WriteLine("I Can Speak Tagalog");
            Console.WriteLine("My Favorite Drink Is Sweet Tea Or Regular Tea");
            Console.WriteLine("My Favorite Fast Food Restaurant is Taco Bell");
            Console.WriteLine("My Least Favorite Fast Food Restaurant is McDonalds");
            Console.WriteLine("My Least Favorite Filipino Dish Is Dinuguan");
            Console.WriteLine("My Least Favorite Color Is Red");
            Console.WriteLine("I Don't Give Up Easily");
            Console.WriteLine("I Ask For Help Instead Of Being Stuck");
            Console.WriteLine("I Value Discipline");
            Console.WriteLine("I Want To Get A Job In The Data Type Fields");
            Console.WriteLine("I Prefer A Structured Learning Style");
            Console.WriteLine("I Focus On Self-Improvement");
            Console.WriteLine("I Think A Lot About The Future");
            Console.WriteLine("I Care About My Personal Growth");
            Console.WriteLine("My Prefered Learning Style");
            Console.WriteLine("I Admire Being Consistent");
            Console.WriteLine("I Want To Be Depandable");
            Console.WriteLine("I Value Honesty");
            Console.WriteLine("I Want Stability In The Future");
            Console.WriteLine("I Like To Prove Something For Myself");
            Console.WriteLine("I Prefer Meaningful Conversations");
            Console.WriteLine("I Don't Mind Starting From Nothing");
            Console.WriteLine("I Love Getting Out Of My Comfort Zone");
            Console.WriteLine("I Like Having A Road Map");
            Console.WriteLine("I Want My Efforts To Pay Off In The Future");
            Console.WriteLine("I Want To Feel In Control Of My Future");
            Console.WriteLine("I Am Proud Of My Work Ethic");
            Console.WriteLine("I Want To Become The Very Best Version Of Myself");
            Console.WriteLine("I Care About Doing Things The Right Way");
            Console.WriteLine("I Am Really In Technology Or Computers On How They Work");
            Console.WriteLine("I Want To Learning Coding Seriously");
            Console.WriteLine("I Love Doing Projects While Learning");
            Console.WriteLine("I Hate Being Lost Or Being Unprepared");
            Console.WriteLine("I Care About My Long-Term Results");
            Console.WriteLine("I Like Buidling Skills That Last");
            Console.WriteLine("I Love Doing Things The Right Way");
            Console.WriteLine("I Love Funko Pops");
            Console.WriteLine("I'm Fascinated About How People Think Differently");
            Console.WriteLine("I'm Very Patient On Tackling A Complex Problem");
            Console.WriteLine("I Like Clarity");
            Console.WriteLine("I Try To Understand Myself Better");
            Console.WriteLine("I Prefer Learning More Than Memorizing the Materials");
            Console.WriteLine("I Love Asking Why Even If The Problem Is Not Complex");
            Console.WriteLine("I Care About My Improvement");
            Console.WriteLine("I Love Challenging Myself");
            Console.WriteLine("I Enjoy Looking At Patterns");
            Console.WriteLine("I Love Simple Explanations");
            Console.WriteLine("I Like When Things Make Sense");
            Console.WriteLine("I Play Video Games To Relax");
            Console.WriteLine("I'm Proud Of Getting Out Of My Comfort Zone");
            Console.WriteLine("I'm Currently Finding A Way To Focus Better");
            Console.WriteLine("I Struggle The Most On Critical Thinking");
            Console.WriteLine("I Feel Bored When Teachers Talk And Don't Teach Visually");
            Console.WriteLine("I Am A Visual Learner");
            Console.WriteLine("I Feel Accomplished When I Don't Have To Worry About Anything");
            Console.WriteLine("I Admire People Who Follow Their Goals");
            Console.WriteLine("I Try To Understand The World Better");
            Console.WriteLine("I Try To Become More Self Aware");
        }
    }
}
